name       : clipit
version    : 1.4.5
release    : 7
homepage   : https://github.com/shantzu/ClipIt
source     :
    - https://github.com/CristianHenzel/ClipIt/archive/v1.4.4.tar.gz : f17bd2f00ece505510428de23f3e84424c62043d95bd9c62f5d28fe4bcf7ecdb
license    : GPL-3.0-or-later
component  : desktop
summary    : ClipIt is a lightweight GTK+ clipboard manager.
builddeps  :
    - pkgconfig(gtk+-2.0)
description: |
    ClipIt is a lightweight GTK+ clipboard manager.
setup      : |
    sh autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
    # Remove global autostart
    rm %installroot%/etc/xdg/autostart/clipit-startup.desktop
