name       : clipit
version    : 1.4.2
release    : 2
homepage   : https://github.com/shantzu/ClipIt
source     :
    - http://internode.dl.sourceforge.net/project/gtkclipit/Version%201/clipit-1.4.2.tar.gz : 6a63c7c4c39b423a266907e5b76f7d16301b164437dc7635cf25ace730b23c4b
license    : GPL-3.0
summary    : ClipIt is a lightweight GTK+ clipboard manager.
builddeps  :
    - pkgconfig(gtk+-2.0)
description: |
    ClipIt is a lightweight GTK+ clipboard manager.
setup      : |
    sh autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
    # Remove global autostart
    rm %installroot%/etc/xdg/autostart/clipit-startup.desktop
