name       : clipit
version    : 1.4.5
release    : 9
homepage   : https://github.com/shantzu/ClipIt
source     :
    - https://github.com/CristianHenzel/ClipIt/archive/refs/tags/v1.4.5.tar.gz : f0bbd1b4ff07bb4509388cf5b7f7a25fd72ec02cdd8f4c8f5ff3f5f9ca6da514
license    : GPL-3.0-or-later
component  : desktop
summary    : ClipIt is a lightweight GTK+ clipboard manager.
description: |
    ClipIt is a lightweight GTK+ clipboard manager.
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(gtk+-3.0)
setup      : |
    %autogen --with-gtk3 --enable-appindicator
build      : |
    %make
install    : |
    %make_install
    # Remove global autostart
    rm %installroot%/etc/xdg/autostart/clipit-startup.desktop
